### ISSUE TITLE
Schreiben des Pflichtenheftes

### ISSUE THREAD

**Issue by micgro42** [fa35/Arbeitszeitdokumentation#1]
Arbeitsaufteilung
Gruppennummer
GUI- / Konsolenskizze
Testszenarien
Meilensteine
Problemstellung
Datenhaltung
ER-Modell

**Comment by ghost** [comment]
Zu den Testsezenarien: Macht doch nen Schreibtischtest, der kostet nicht so viel Zeit. Einfach eine Tabelle mit Dingen anlegen die ihr testen wollt, quasi wie ne Todo-Liste. Da steht dann sowas wie das der Speicher-Button funktionieren soll. Getestet wird das über das Klicken auf den Button, mit der Erwartung das beim nächsten Mal öffnen oder sowas, die hoffentlich gespeicherten Einträge sichtbar sind. Also erstellt ihr 2-3 Testprotokolle, die dann quasi ne Check-Liste darstellen.

**Comment by ghost** [comment]
Denkt an das Pflichtenheft. Das alleine ist bei unserer Aufgabenstellung 2-3 Seiten lang, ohne Inhaltsverzeichnis und Anhang. Das ist nochmal viel Arbeit und man muss ja auch den Unterschied zwischen dem Pflichtenheft und der eigentlichen Dokumentation bzw. zuvor zur Mini-Dokumentation sehe.

**Comment by ghost** [comment]
für Mockups oder Diagramme benutzt meine Gruppe, DIA und die ein oder andere Website oder auch Gliffy. Diagramme gehören meistens in den Anhang, sehen aber super aus und es wirkt so, als hätte man nicht einfach irgendwas herunterprogrammiert, sonder erst einen mega Plan gemacht.

**Comment by micgro42** [comment]
done
