### ISSUE TITLE
Erstellung 1. Datenhaltung

### ISSUE THREAD

**Issue by micgro42** [fa35/Arbeitszeitdokumentation#4]
Datenbank oder andere Variante

**Comment by ghost** [comment]
ihr könnt auf jeden Fall mysql nehmen, egal womit ihr programmiert

**Comment by ghost** [comment]
falls ihr euch bei C# herumtreibt: www.codeplanet.eu/tutorials/csharp/5-verbindung-zum-mysql-server-mit-csharp.html
